### ISSUE TITLE
Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1 

### ISSUE THREAD

**Issue by Ianmcmill** [akanimax/MSG-GAN#5]
I am not sure what is the important error.
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1 at c:\new-builder_3\win-wheel\pytorch\aten\src\th\generic/THTensorMath.cpp:3616

or 

RuntimeError: Couldn't open shared event: <torch_5308_2995310656_event>, error code: <2>

I converted the images to RGB with
`mogrify -colorspace RGB *.jpg`
but that didn't help.
Any hints?

```
Starting the training process ...

Epoch: 1
Elapsed [0:00:08.859118] batch: 1  d_loss: 2.000845  g_loss: 3.779521
Elapsed [0:00:10.685150] batch: 3  d_loss: 0.985300  g_loss: 4.276993
Elapsed [0:00:13.235160] batch: 6  d_loss: 1.903335  g_loss: 3.318109
Elapsed [0:00:15.852519] batch: 9  d_loss: 1.755461  g_loss: 3.607772
Traceback (most recent call last):
  File "train.py", line 221, in <module>
    main(parse_arguments())
  File "train.py", line 215, in main
    start=args.start
  File "F:\portrait\MSG-GAN\sourcecode\MSG_GAN\GAN.py", line 423, in train
    for (i, batch) in enumerate(data, 1):
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\utils\data\dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\utils\data\dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\utils\data\dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\utils\data\dataloader.py", line 164, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 1 in dimension 1 at c:\new-builder_3\win-wheel\pytorch\aten\src\th\generic/THTensorMath.cpp:3616

Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x000002C3EC473978>>
Traceback (most recent call last):
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\utils\data\dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\utils\data\dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "c:\users\castle\appdata\local\programs\python\python36\Lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\castle\Envs\keras_tut\lib\site-packages\torch\multiprocessing\reductions.py", line 167, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: Couldn't open shared event: <torch_5308_2995310656_event>, error code: <2>
```

**Comment by akanimax** [comment]
Hi @Ianmcmill,

In your images folder (dataset) some are RGB images and some are Single Channel grayscale images. The code / architecture requires the images to be RGB always. So, either you need to filter the grayscale images or convert them to RGB by channel replication.
Hope this helps

Cheers :beers:!
@akanimax

**Comment by akanimax** [comment]
@Ianmcmill, Closing this now. Let me know if you still need help.

Best regards,
@akanimax
